title: Lambert Intellectual Property Law
tagline:
description:
author:
baseurl:
url: http://www.lambertlaw.ca

markdown: rdiscount
permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

sass:
  sass_dir: _scss
  style: compressed

collections:
  pages:
    output: true
    permalink: /
